name: booking_system_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  nb_utils: ^4.4.12
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  cached_network_image: ^3.2.0
  google_fonts: ^2.3.1
  flutter_vector_icons: ^1.0.0
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  image_picker: ^0.8.4+10
  flutter_staggered_grid_view: ^0.6.1
  date_time_picker: 2.1.0
  url_launcher: ^6.0.20
  onesignal_flutter: ^3.2.8
  photo_view: ^0.13.0
  flutter_rating_bar: ^4.0.0
  package_info: ^2.0.2
  clippy_flutter: 2.0.0-nullsafety.1
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.2
  file_picker: ^4.4.0
  flutter_svg: ^1.0.3
  readmore: 2.1.0
  flutter_staggered_animations: 1.0.0
  permission_handler: ^9.2.0
  flutter_custom_tabs: ^1.0.4

  google_sign_in: ^5.2.4
  firebase_crashlytics: ^2.5.1
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_storage: ^10.2.7
  firebase_database: ^9.0.6

  cloud_firestore: ^3.1.10

  # PAYMENTS
  flutter_stripe: ^2.3.0
  razorpay_flutter: ^1.2.9
  flutter_paystack: ^1.0.5+1
  flutterwave_standard: 1.0.3
  flutterwave: ^1.0.1

  ## Map
  google_maps_flutter: ^2.1.2
  geolocator: ^8.2.0
  geocoding: ^2.0.2

  paginate_firestore: ^1.0.3

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - images/icons/
    - images/
    - images/flag/
    - images/app_images/
    - images/icons/
